#ifndef GAMENETWORK_CONFIG_H
#define GAMENETWORK_CONFIG_H

#define GNS_DEFAULT_KEEPALIVE_INTERVAL 30 // saniye
#define GNS_MAX_CLIENTS 128
#define GNS_KEEPALIVE_MESSAGE "GNS_KEEPALIVE"
#define GNS_KEEPALIVE_MESSAGE_LEN 13
#define GNS_CLIENT_TIMEOUT 60 // saniye

#endif // GAMENETWORK_CONFIG_H 